CREATE TABLE IF NOT EXISTS menu(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects(
id INTEGER PRIMARY KEY AUTOINCREMENT,
project TEXT NOT NULL,
text TEXT NOT NULL,
url TEXT NOT NULL,
time INTEGER NOT NULL
);

